name: seattle_airbnb
dependencies:
  - ipykernel
  - geopandas
  - matplotlib
  - notebook
  - numpy
  - openpyxl
  - pandas
  - plotly
  - pylint
  - python
  - pip
  - seaborn
  - scikit-learn
  - xgboost
  - xlrd